texts = [
    "Amazon is expanding its logistics network in Europe.",
    "The new iPhone model is expected to release next month.",
    "Tesla's new battery technology promises longer ranges.",
    "Microsoft announced a new AI research center in China.",
    "The government is considering new regulations for cryptocurrencies.",
    "Facebook is facing a lawsuit over data privacy concerns.",
    "Uber is launching a new service in New York City.",
    "The Supreme Court ruled on the controversial case today.",
    "Walmart's earnings report exceeded Wall Street expectations.",
    "NASA successfully landed a rover on Mars.",
    "The stock market saw significant gains in tech stocks today.",
    "Airbnb's IPO was one of the most successful in history.",
    "The education department announced new student loan forgiveness plans.",
    "A new COVID-19 variant has been detected in South Africa.",
    "Google introduced new privacy features in its latest update.",
    "Twitter permanently banned a high-profile user for violating terms.",
    "Sony's latest gaming console sold out within minutes of release.",
    "The city council passed new environmental regulations.",
    "IBM is partnering with universities to advance quantum computing.",
    "A major earthquake struck the coast of Japan this morning."
]

labels = [
    "business",
    "business",
    "technology",
    "technology",
    "policy",
    "business",
    "business",
    "policy",
    "business",
    "science",
    "business",
    "business",
    "policy",
    "health",
    "technology",
    "business",
    "business",
    "policy",
    "technology",
    "news"
]
